# #############################################################################
# Example 19 — Remove numbered temporary files
# Real-life scenario: Clean up predictable temporary files generated by testing.
# #############################################################################

$path = "C:\Temp\ForLoopTest"

for ($i = 1; $i -le 5; $i++) {
    $file = Join-Path $path "test-$i.txt"

    if (Test-Path $file -PathType Leaf) {
        Remove-Item $file
        Write-Output "Removed: $file"
    }
    else {
        Write-Output "Not found: $file"
    }
}
